### ISSUE TITLE
Unable to resolve testable http ip

### ISSUE THREAD

**Issue by FrederikHaa** [gallofeliz/openvpn-client#1]
Hello,

I'm trying to use your container using my IPVanish account
Right now I am only starting the client using the first docker-compose file in the readme.
I have copied the provided .ovpn and created a .ovpn-pass.

When I run docker compose and look in the log file, I see the following:

```
vpn-client | 2018-11-23T09:46:47.898328780Z Resolving config ...
vpn-client | 2018-11-23T09:46:47.917911854Z sh: 216.239.34.21: unknown operand
vpn-client | 2018-11-23T09:46:47.918066408Z Unable to resolve testable http ip
vpn-client exited with code 3
```

docker-compose.yml:
```
version: '3.5'
services:
  vpn:
    container_name: vpn-client
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
     - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./ipvanish.ovpn:/usr/local/etc/.ovpn:ro
      - ./ipvanish.ovpn-pass:/usr/local/etc/.ovpn-pass:ro
      - ./ipvanish.crt:/usr/local/etc/ipvanish.crt:ro
networks:
  default:
      name: vpn-network
```

ipvanish.ovpn:
```
client
dev tun
proto udp
remote cph-c04.ipvanish.com 443
resolv-retry infinite
nobind
persist-key
persist-tun
persist-remote-ip
ca ipvanish.crt
verify-x509-name cph-c04.ipvanish.com name
auth-user-pass
comp-lzo
verb 3
auth SHA256
cipher AES-256-CBC
keysize 256
tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA:TLS-DHE-DSS-WITH-AES-256-CBC-SHA:TLS-RSA-WITH-AES-256-CBC-SHA
```

ipvanish.ovpn-pass
```
[USERNAME]
[PASSWORD]
```
